################# Tomcat 配置 ##################
server:
  port: 7000
  servlet:
    context-path: /mall
  tomcat:
    uri-encoding: utf-8

################# MybatisPlus 配置 ##################
mybatis-plus:
  type-aliases-package: com.ratel.hydra.**.po
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false
    db-config:
      select-strategy: not_empty

################# AOP 配置 ##################
  aop:
    proxy-target-class: true

################# Spring 配置 ##################
spring:
  profiles:
    active: dev